### ISSUE TITLE
Apple Silicon (M1) support for all paketo-buildpacks Builder

### ISSUE THREAD

**Issue by klopfdreh** [paketo-buildpacks/base-builder#652] opened 2022-12-08 17:05 UTC
## Describe the Enhancement
As a customer I want to be able to have Full Builder / Base Builder / Tiny Builder available for linux/arm64.

As I can see at docker hub all images are only available for linux/amd64 (os/arch). Example: https://hub.docker.com/r/paketobuildpacks/builder/tags

There are already solutions for linux/arm64 (os/arch). Example: https://hub.docker.com/r/dashaun/java-native-builder-arm64/tags

## Possible Solution
Change the "release" GitHub-Actions so that also Images for linux/arm64 are published at the same tag for a different arch, so that consumers can pull it like `docker pull --platform linux/arm64 paketobuildpacks/builder:latest` like in `spring-boot-maven-plugin`.

Maybe the tomls can somehow be parameterized in those Actions and a loop can be created to publish each arch.

## Motivation
As a Spring Boot 3 user I want to be able to create arm64 native images officially maintained by paketo like in this maven example:
```xml
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <image>
            <builder>paketobuildpacks/builder:tiny</builder>
            <env>
                <BP_NATIVE_IMAGE>true</BP_NATIVE_IMAGE>
            </env>
        </image>
    </configuration>
    <executions>
        <execution>
            <id>process-aot</id>
            <goals>
                <goal>process-aot</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
Currently I have to change the builder to `<builder>dashaun/java-native-builder-arm64</builder>`

Note: I hope I didn't miss a ticket which is already opened for that topic.
Note2: This ticket might be not created at the right repository as it belongs to all builders.

**Comment by bclozel** [comment] 2022-12-09 08:20
Possible duplicate of buildpacks/lifecycle#435

**Closed** 2023-07-19 22:25 UTC
